# Plant monitoring systems

# Automations for notifications
automation: !include_dir_merge_list automations

homeassistant:
  customize:
    plant.1:
      friendly_name: 🪜Attic
      icon: mdi:leaf
    #plant.2:
    #  friendly_name: 🦋Butterfly
    #  icon: mdi:butterfly
    plant.3:
      friendly_name: 🍽️Dining
      icon: mdi:stairs

# Using numbers instead of names:
# - only configure names in the UI, making plant changes easy
# - try rendering the friendly_name of the plant everywhere, not all cards support that though
# - the physical sensors are marked with the number
plant:

  # Ecowitt WH51 soil sensor
  1:
    sensors:
      moisture: sensor.plant_1_moisture
      temperature: sensor.netatmo_attic_temperature
      # First needs conversion from volt to percent (use template sensor)
      #battery: sensor.plant_1_battery
    # TODO: figure this out
    min_moisture: 20 # TODO: extract to a file?
    max_moisture: 60
    min_temperature: 5
    max_temperature: 40

  # Using the Xiaomi plant sensor XL
  #2:
  #  sensors:
  #    moisture: sensor.plant_2_moisture
  #    brightness: sensor.plant_2_illuminance
  #    temperature: sensor.plant_2_temperature
  #    #battery: not available, it should have this though?
  #  min_moisture: 70
  #  # Just as a warning, not
  #  min_temperature: -10

  # Ecowitt WH51 soil sensor
  3:
    sensors:
      moisture: sensor.plant_3_moisture
      brightness: sensor.living_room_motion_sensor_illuminance_lux
      temperature: sensor.ecowitt_wh45_temperature
      # First needs conversion from volt to percent (use template sensor)
      #battery: sensor.plant_3_battery
    # TODO: figure this out
    min_moisture: 15
    max_moisture: 60
    min_temperature: 10
    max_temperature: 30
