# Plant monitoring systems

# Automations for notifications
automation: !include_dir_merge_list automations

plant:
  # Using the Ecowitt soil sensor
  bonsai:
    sensors:
      moisture: sensor.ecowitt_soil_bonsai_moisture
      brightness: sensor.living_room_motion_sensor_illuminance
      temperature: sensor.ecowitt_wh45_temperature
      # First needs conversion from volt to percent (use template sensor)
      #battery: sensor.ecowitt_soil_bonsai_battery
    # TODO: figure this out
    min_moisture: 15
    max_moisture: 60

    min_temperature: 10
    max_temperature: 30
    # TODO: Brightness range?

  # Using the Xiaomi plant sensor XL
  palm_big:
    sensors:
      moisture: sensor.palm_big_moisture
      brightness: sensor.palm_big_illuminance
      temperature: sensor.palm_big_temperature
      #battery: not available, it should have this though?
    min_moisture: 70
    # Otherwise freezes too death
    min_temperature: -5

  # Using the Xiaomi Plant Sensor
  amaryllis:
    sensors:
      moisture: sensor.amaryllis_moisture
      battery: sensor.amaryllis_battery
      temperature: sensor.amaryllis_temperature
      conductivity: sensor.amaryllis_conductivity
      brightness: sensor.amaryllis_light_intensity

    min_moisture: 15
    max_moisture: 60

    min_conductivity: 350
    max_conductivity: 2000

    min_temperature: 5
    max_temperature: 35

    min_brightness: 2000
    max_brightness: 35000

    min_battery: 20
