# Automations to switch between states
automation: !include_dir_merge_list automations

# Implements home cinema modes:
# - Off: tv/receiver/etc are off
# - Chromecast: view/listen to chromecast content
# - Bluetooth: listen to bluetooth music
# - TV: view T-mobile linear tv

# Tracker of the current state
input_select:
  home_cinema_mode:
    name: Home cinema mode
    icon: mdi:speaker-multiple
    options:
      - 'off'
      - 'chromecast'
      - 'bluetooth'
      - 'tv'
      - 'laptop'
      - 'steamLink'
      - 'raspberryPi'
      - 'unknown'

# Tracks whether we are moving towards a new state
input_boolean:
  home_cinema_pending:
    name: Home cinema changing state
    icon: mdi:loading
    initial: "off" # Assume not loading after restart

# Script for changing between modes
script:
  home_cinema_mode: !include scripts/set_mode.yaml

  home_cinema_off: !include scripts/off.yaml
  home_cinema_chromecast: !include scripts/chromecast.yaml
  home_cinema_bluetooth: !include scripts/bluetooth.yaml
  home_cinema_tv: !include scripts/tv.yaml
  home_cinema_laptop: !include scripts/laptop.yaml
  home_cinema_steam_link: !include scripts/steam_link.yaml
  home_cinema_raspberry_pi: !include scripts/raspberry_pi.yaml

# Onkyo integration
media_player:
  - platform: onkyo
    host: 10.0.2.1
    name: receiver
    receiver_max_volume: 100
    sources:
      # To figure these out:
      # 1. install https://github.com/miracle2k/onkyo-eiscp
      # 2. run `onkyo --host 192.168.0.100 source=query` when on a source you need to the name for
      cd: TV
      video3: Bluetooth
      video2: T-Mobile
      video6: Raspberry Pi
      dvd: Steam link
  # Api is pretty broken after a few calls, and unplugged the cable to get rid of annoying extra ChromeCast device
  # - platform: philips_js
  #   host: 10.0.2.22
  #   name: TV
  #   api_version: 6

# HDMI-CEC plugin to control connected devices
# - Raspberry pi is connected to the Receiver using HDMI
# - Host points to a supervisor addon, see readme.md
hdmi_cec:
  host: 58c14403-pi-cec
  platform: media_player
  # HDMI network layout as seen from the TV
  devices:
    TV: 0.0.0.0
    Receiver: 1.0.0.0
    # Connected to the receiver
    T-Mobile: 1.3.0.0
    Steam link: 1.4.0.0
    Raspberry Pi: 1.7.0.0

    Laptop: 2.0.0.0
    Chromecast: 3.0.0.0
