# Automations to switch between states
automation: !include_dir_merge_list automations

# Implements home cinema modes:
# - Off: tv/receiver/etc are off
# - Chromecast: view/listen to chromecast content
# - Bluetooth: listen to bluetooth music
# - TV: view T-mobile linear tv

# Tracker of the current state
input_select:
  home_cinema_mode:
    name: Home cinema mode
    icon: mdi:speaker-multiple
    options:
      - 'off'
      - 'chromecast'
      - 'bluetooth'
      - 'tv'
      - 'laptop'
      - 'steamLink'
      - 'raspberryPi'
      - 'unknown'

# Tracks whether we are moving towards a new state
input_boolean:
  home_cinema_pending:
    name: Home cinema changing state
    icon: mdi:loading
    initial: "off" # Assume not loading after restart

# Script for changing between modes
script:
  home_cinema_mode: !include scripts/set_mode.yaml

  home_cinema_chromecast: !include scripts/chromecast.yaml
  home_cinema_bluetooth: !include scripts/bluetooth.yaml
  home_cinema_tv: !include scripts/tv.yaml
  home_cinema_laptop: !include scripts/laptop.yaml
  home_cinema_steam_link: !include scripts/steam_link.yaml
  home_cinema_raspberry_pi: !include scripts/raspberry_pi.yaml

media_player:
  # Api is pretty broken after a few calls, and unplugged the cable to get rid of annoying extra ChromeCast device
  # - platform: philips_js
  #   host: 10.0.2.22
  #   name: TV
  #   api_version: 6

  # Combined media player for the Google TV Streamer:
  # - part of the chromecast integration
  # - part of the android tv remote integration
  # https://www.home-assistant.io/integrations/universal/
  - platform: universal
    name: Google TV Streamer
    unique_id: google_tv_streamer
    device_class: tv
    children:
      - media_player.google_tv_streamer_android_tv_remote
      - media_player.google_tv_streamer_cast
    browse_media_entity: media_player.google_tv_streamer_cast
    commands:
      turn_off:
        action: media_player.turn_off
        data:
          entity_id: media_player.google_tv_streamer_android_tv_remote
      turn_on:
        action: media_player.turn_on
        data:
          entity_id: media_player.google_tv_streamer_android_tv_remote
      volume_up:
        action: media_player.volume_up
        data:
          entity_id: media_player.google_tv_streamer_android_tv_remote
      volume_down:
        action: media_player.volume_down
        data:
          entity_id: media_player.google_tv_streamer_android_tv_remote

# Data fields for button that goes to the currently playing media content
input_text:
  home_cinema_media_icon:
    name: Home cinema media icon
    icon: mdi:video-4k-box
  home_cinema_media_uri:
    name: Home cinema media uri
    icon: mdi:link