automation: !include_dir_merge_list automations

# State tracker
input_select:
  washing_machine:
    name: Washing machine
    initial: "Off"
    options:
      # ~0-0.5 watt while off
      - "Off"
      # ~5.4 watt while turned on but doing nothing
      - "Idle"
      # Power states:
      # - ~37 watt while starting up
      # - ~1800-1900 watt while heating water
      # - ~5-150 watt while pumping water and rotating
      # - ~250 watt for centrifuge at 1400 rpm
      - "Running"
      # Meaning it still needs to be emptied (power usage might be Off/Idle, or actually Running when already started a new round before marking emptied)
      - "Done"
    icon: mdi:washing-machine
