# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Entity customizations
homeassistant:
  customize:
    person.thijs:
      entity_picture: "/local/thijs.jpg"
    person.frits:
      entity_picture: "/local/frits.jpg"
  packages:
    computer: !include features/computer/definitions.yaml
    crisp: !include features/crisp/definitions.yaml
    curtain: !include features/curtain/definitions.yaml
    electricity: !include features/electricity/definitions.yaml
    gardening: !include features/gardening/definitions.yaml
    guests: !include features/guests/definitions.yaml
    home_cinema: !include features/home_cinema/definitions.yaml
    lighting: !include features/lighting/definitions.yaml
    meters: !include features/meters/definitions.yaml
    network: !include features/network/definitions.yaml
    presence: !include features/presence/definitions.yaml
    system: !include features/system/definitions.yaml
    spotify: !include features/spotify/definitions.yaml
    vacuum: !include features/vacuum/definitions.yaml
    weather: !include features/weather/definitions.yaml
    washing_machine: !include features/washing_machine/definitions.yaml

    ##### DISABLED
    # party_lighting: !include features/party_lighting/definitions.yaml
    # corona: !include features/corona/definitions.yaml
    # queing: !include features/queing/definitions.yaml

# Include themes
frontend:
  themes: !include_dir_merge_named themes
  # This has better performance than adding in lovelace-resources according to the author
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Setup SSL
http:
  use_x_forwarded_for: true
  trusted_proxies:
    # Localhost, just to be sure
    - 127.0.0.1
    # Local docker network (add-ons like nginx proxy manager)
    - 172.16.0.0/12

# Setup history database (MariaDB addon)
recorder:
  db_url: !secret mariadb_connection
  commit_interval: 10
  purge_keep_days: 7
  auto_purge: true
  exclude:
    domains:
      # No need for history of vacuum map and such
      - camera
      # Not using weather history, just current predictions
      - weather
      # Not using history, updates every few seconds while playing
      - media_player
    entities:
      # Triggers often, no need for history
      - automation.detect_motion_in_the_living_room
      # No need for a long history
      - binary_sensor.living_room_motion_sensor_occupancy
      - sensor.computer_thijs_last_active
      - sensor.neerslag_buienalarm_regen_data
      # Stores raw orders from Crisp, can be huge, only derived sensors are needed
      - sensor.crisp_next_orders
      # Stores 1 raw order from Crisp
      - sensor.crisp_next_order_input
    entity_globs:
      # Change very often, maybe remove completely?
      - sensor.glances_*
  include:
    entities:
      # Showing a graph of this, keep history
      - sensor.glances_cpu_thermal_1_temp
      - sensor.glances_cpu_used_2
# Query for checking entity that update the most:
# select
#   entity_id,
#   count(*)
# from states
# where
#   last_updated >= (UTC_TIMESTAMP - interval 2 hour)
# group by entity_id
# order by count(*) desc, entity_id
# limit 100


# Text to speech
tts:
  # Baseline tts voice, does not sound great
  - platform: google_translate
  - platform: google_cloud
    key_file: credentials/google_cloud_tts.json
    voice: en-US-Wavenet-D # Male, kinda deep voice
    encoding: ogg_opus # Other options: linear16, mp3
    speed: 1.15 # Speed up a bit
    # pitch: -2.5
    # gain: -5.0

automation: !include automations.yaml
script: !include scripts.yaml

# Frontend settings
lovelace:
  # Set the main dashboard to use the yaml configured UI, this is shown as default
  mode: yaml
  resources: !include lovelace_resources.yaml

# REST commands
rest_command:
  tv_input:
    url: http://10.0.2.22:1925/6/input/key
    method: POST
    payload: '{"key": "{{ key }}"'
    content_type: "application/json"
  chromecast_boot_tv:
    url: http://10.0.2.12:8008/apps/ChromeCast
    method: POST

# Mailgun email
notify:
  - name: email_thijs
    platform: smtp
    server: smtp.mailgun.org
    port: 587
    timeout: 15
    sender: !secret mailgun_smtp_user
    username: !secret mailgun_smtp_user
    password: !secret mailgun_smtp_password
    recipient: !secret email_thijs
    sender_name: Home Assistant

# No ip (disabled, already handled by the Unifi USG)
#no_ip:
#  domain: !secret no_ip_domain
#  username: !secret no_ip_username
#  password: !secret no_ip_password

sensor:
  - platform: time_date
    display_options:
      - "date"
      - "date_time_iso"

logger:
  default: warning
  #logs:
  #  goslideapi: debug
  #  custom_components.slide: debug
  #  homeassistant.components.slide: debug