title: "Home"
custom_header:
  compact_mode: true
  footer_mode: false
  menu_hide: true
  reverse_button_direction: true
  reverse_tab_direction: true
views:
  # Home screen
  - icon: "mdi:theater"
    path: living-room
    cards:
      - !include features/presence/ui/person_locations.yaml
      - !include features/lighting/ui/living_room.yaml
      - !include features/home_cinema/ui/mode-select.yaml
      - !include features/home_cinema/ui/players.yaml
      - !include features/crisp/ui/next_order.yaml
      - !include features/washing_machine/ui/summary.yaml
      - type: horizontal-stack
        cards:
          - !include features/weather/ui/living_room_summary.yaml
          - !include features/weather/ui/garden_summary.yaml
      - type: horizontal-stack
        cards:
          - !include features/weather/ui/thijs_summary.yaml
          - !include features/weather/ui/frits_summary.yaml
          - !include features/weather/ui/computers_summary.yaml
      - !include features/electricity/ui/summary.yaml
      - !include features/vacuum/ui/summary.yaml
      # Maintenance column
      - type: vertical-stack
        cards:
          # Might be an immediate thing
          - !include features/system/ui/problems.yaml
          # Kinda short-term: might get unavailable later
          - !include features/system/ui/battery_low.yaml
          # Longer term, can wait
          - !include features/system/ui/primary_updates.yaml
          - !include features/system/ui/secondary_updates.yaml

      # - !include features/weather/ui/buienalarm.yaml, Constantly broken, look for fix
      # - !include ui/media/plex-status.yaml, not useful yet

    # More info popup replacements
    popup_cards:
      sensor.thijs_location: !include features/presence/ui/thijs_location_popup.yaml
      sensor.frits_location: !include features/presence/ui/frits_location_popup.yaml


  # Thijs
  - title: Thijs
    path: thijs
    badges: []
    cards:
      - !include features/lighting/ui/room_thijs.yaml
      - !include features/presence/ui/thijs_sleepy.yaml
      - !include features/computer/ui/computer_thijs.yaml
      - !include features/electricity/ui/computer_thijs.yaml
      - !include features/spotify/ui/thijs.yaml

  # Frits
  - title: Frits
    path: frits
    badges: []
    cards:
      - !include features/lighting/ui/room_frits.yaml
      - type: entities
        entities:
          - device_tracker.unifi_phone_frits
          - sensor.phone_frits_battery_level
          - sensor.phone_frits_battery_state
          - sensor.phone_frits_bssid
          - sensor.phone_frits_connection_type
          - sensor.phone_frits_geocoded_location
          - sensor.phone_frits_last_update_trigger
          - sensor.phone_frits_ssid
          - sensor.phone_frits_storage

  # Plants
  #- icon: mdi:sprout
  #  path: plants
  #  cards:
  #    - !include features/gardening/ui/plant.yaml

  # Lighting
  - icon: mdi:lightbulb
    path: lights
    badges: []
    cards:
      - !include features/lighting/ui/floor_0.yaml
      - !include features/lighting/ui/floor_1.yaml
      - !include features/lighting/ui/floor_2.yaml

# Templates for type:custom-button
button_card_templates:
  # Card header that can be tapped
  header:
    styles:
      card:
        - padding: 16px 16px 0 16px
        - box-shadow: 'none'
      name:
        - justify-self: start
        - font-size: 24px
      label:
        - justify-self: start
  header_standalone:
    color: transparent
    color_type: card
    styles:
      card:
        - padding: 20px 16px 8px 16px
        - margin-bottom: -8px
        - box-shadow: 'none'
      name:
        - font-size: 20px

  # Small button with a statistic
  statistic_button:
    show_state: true
    show_icon: false
    styles:
      card:
        - padding-bottom: 0.8rem
        - height: 58px
      name:
        - font-size: 0.8rem
        - text-transform: uppercase
        - opacity: 0.7
        - margin-bottom: 2px
      state:
        - font-size: 1.3rem

  # Humidity state color
  statistic_button_humidity:
    template: statistic_button
    color_type: card # Use the color as card background
    state:
      # Bad states
      - value: 20
        operator: "<"
        color: "#790000"
      - value: 70
        operator: ">"
        color: "#790000"
      # Not-ideal states
      - value: 30
        operator: "<"
        color: "#ab6300"
      - value: 60
        operator: ">"
        color: "#ab6300"
      # Good state
      - operator: "default"
        color: "var( --ha-card-background, var(--card-background-color, white) )"

  # CO2 state color
  statistic_button_co2:
    template: statistic_button
    color_type: card # Use the color as card background
    state:
      # Bad state
      - value: 1000
        operator: ">"
        color: "#790000"
      # Worrisome state
      - value: 800
        operator: ">"
        color: "#ab6300"
      # Good state
      - operator: "default"
        color: "var( --ha-card-background, var(--card-background-color, white) )"

  # Home Cinema mode buttons
  home_cinema_mode:
    # Use color as card background instead of state text color
    color_type: card
    # iOS only feedback when pressing
    haptic: light
    # Square buttons
    aspect_ratio: 1/1
    # Custom styling
    styles:
      name:
        # Smaller names to fit more buttons
        - font-size: 0.9rem
      lock:
        # Smaller lock (from 24px)
        - width: 16px

  # Tiny button for switching to less-used sources
  home_cinema_mode_tiny:
    template: home_cinema_mode
    show_name: false
    size: 65%
    styles:
      overlay:
        - display: 'none'
      lock:
        - display: 'none'