title: 'Home'
custom_header:
  compact_mode: true
  footer_mode: false
  menu_hide: true
  reverse_button_direction: true
  reverse_tab_direction: true
views:

  # Living room
  - icon: 'mdi:theater'
    path: living-room
    cards:
      - !include features/presence/ui/person_locations.yaml
      - !include features/lighting/ui/living_room.yaml
      - !include features/home_cinema/ui/mode-select.yaml
      - !include features/home_cinema/ui/players.yaml
      #- !include ui/media/plex-status.yaml, not useful yet
      - type: horizontal-stack
        cards:
          - !include features/weather/ui/living_room_summary.yaml
          - !include features/weather/ui/garden_summary.yaml
      - type: horizontal-stack
        cards:
          - !include features/weather/ui/thijs_summary.yaml
          - !include features/weather/ui/frits_summary.yaml
          - !include features/weather/ui/computers_summary.yaml
      - !include features/electricity/ui/summary.yaml
      - !include features/weather/ui/buienalarm.yaml
      # Not used: - !include features/weather/ui/forecast.yaml
      # Maintenance column
      - type: vertical-stack
        cards:
          - !include features/system/ui/battery_low.yaml
          - !include features/system/ui/updates.yaml

  # Thijs
  - title: Thijs
    path: thijs
    badges: []
    cards:
      - !include features/lighting/ui/room_thijs.yaml
      - !include features/computer/ui/computer_thijs.yaml
      - !include features/spotify/ui/thijs.yaml

  # Frits
  - title: Frits
    path: frits
    badges: []
    cards:
      - !include features/lighting/ui/room_frits.yaml
      - type: entities
        entities:
          - device_tracker.unifi_phone_frits
          - sensor.phone_frits_battery_level
          - sensor.phone_frits_battery_state
          - sensor.phone_frits_bssid
          - sensor.phone_frits_connection_type
          - sensor.phone_frits_geocoded_location
          - sensor.phone_frits_last_update_trigger
          - sensor.phone_frits_ssid
          - sensor.phone_frits_storage

  # Plants
  - icon: mdi:sprout
    path: plants
    cards:
      - !include features/gardening/ui/plant.yaml

  # Lighting
  - icon: mdi:lightbulb
    path: lights
    badges: []
    cards:
      - !include features/lighting/ui/floor_0.yaml
      - !include features/lighting/ui/floor_1.yaml
      - !include features/lighting/ui/floor_2.yaml

# Templates for type:custom-button
button_card_templates:
  # Card header that can be tapped
  header:
    styles:
      card:
        - padding: 16px 16px 0 16px
      name:
        - justify-self: start
        - font-size: 24px
      label:
        - justify-self: start
  header_standalone:
    color: transparent
    color_type: card
    styles:
      card:
        - padding: 16px 16px 0 16px
      name:
        - font-size: 18px

  # Small button with a statistic
  statistic_button:
    show_state: true
    show_icon: false
    styles:
      name:
        - font-size: 0.8rem
        - text-transform: uppercase
        - opacity: 0.7
      state:
        - font-size: 1.3rem
      card:
        - padding-bottom: 0.8rem
        - height: 58px

  # Humidity state color
  statistic_button_humidity:
    template: statistic_button
    color_type: card # Use the color as card background
    state:
      # Bad states
      - value: 20
        operator: '<'
        color: '#790000'
      - value: 70
        operator: '>'
        color: '#790000'
      # Not-ideal states
      - value: 30
        operator: '<'
        color: '#ffa500'
      - value: 55
        operator: '>'
        color: '#ffa500'
      # Good state
      - operator: 'default'
        # TODO: would like to fallback to the default, but that is not possible?!
        color: '#004800'

  # CO2 state color
  statistic_button_co2:
    template: statistic_button
    color_type: card # Use the color as card background
    state:
      # Bad state
      - value: 1000
        operator: '>'
        color: '#790000'
      # Worrisome state
      - value: 800
        operator: '>'
        color: '#ffa500'
      # Good state
      - operator: 'default'
        color: '#004800'
