automation: !include_dir_merge_list automations

# Using the Conbee II stick at: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2220048-if00
zha:
  zigpy_config:
    ota:
      # Auto-update Ikea devices (not constantly enabled to prevent sudden auto-update bricking devices)
      #ikea_provider: true
      # Firmware directory for Hue devices (keep enabled, in case new devices get added to the network)
      otau_directory: /config/zigbee_firmware
# Logging that can be enabled to view firmware upgrade checks/progress
#logger:
#  default: info
#  logs:
#    homeassistant.components.zha: debug
#    zigpy: debug


# Script for changing between modes
script:
  living_room_lighting_mode: !include scripts/set_living_room_lighting_mode.yaml
  thijs_bedroom_lights_turn_on: !include scripts/thijs_bedroom_lights_turn_on.yaml
  bedroom_closets_turn_on: !include scripts/bedroom_closets_turn_on.yaml

input_boolean:
  # Indicates if we consider it light outside
  light_outside:
    name: Light outside
    icon: mdi:theme-light-dark

homeassistant:
  customize_glob:
    # TODO: probably just remove? they should have nice defaults already
    # Remotes
    "sensor.remote_*": # TODO phase out legacy, renaming to the one below
      icon: mdi:remote-tv
    "sensor.*_remote":
      icon: mdi:remote-tv

# Light groups
# Note: for some reason these don't support an 'icon' prop, hopefully in newer versions though
light:
  # Living room lights, all of them (light.living_room_lights)
  - platform: group
    name: Living room lights
    entities:
      - light.living_room_ceiling
      - light.dining_ceiling
      - light.kitchen_ceiling
  # Thijs' bedroom lights (light.bedroom_thijs_lights)
  - platform: group
    name: "Bedroom Thijs lights"
    entities:
      #- light.bedroom_ceiling
      - light.bedroom_thijs_bed
  # Attic room lights (light.attic_room_lights)
  - platform: group
    name: "Attic room lights"
    entities:
      - light.attic_beds
      - light.attic_standing

input_select:
  # Living room light mode: determines brightness of all lights
  living_room_lighting_mode:
    name: Living room lighting mode
    icon: mdi:brightness-4
    options:
      - 'manual'
      - 'day'
      - 'cooking'
      - 'evening'
      - 'night'
