automation: !include_dir_merge_list automations

# Using the Conbee II stick at: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2220048-if00
zha:
  zigpy_config:
    ota:
      # Auto-update Ikea devices (not constantly enabled to prevent sudden auto-update bricking devices)
      #ikea_provider: true
      # Firmware directory for Hue devices (keep enabled, in case new devices get added to the network)
      otau_directory: /config/zigbee_firmware
# Logging that can be enabled to view firmware upgrade checks/progress
#logger:
#  default: info
#  logs:
#    homeassistant.components.zha: debug
#    zigpy: debug


# Script for changing between modes
script:
  living_room_lighting_mode: !include scripts/set_living_room_lighting_mode.yaml
  thijs_bedroom_lights_turn_on: !include scripts/thijs_bedroom_lights_turn_on.yaml
  toilet_light_turn_on: !include scripts/toilet_light_turn_on.yaml

input_boolean:
  # Indicates if we consider it light outside
  light_outside:
    name: Light outside
    icon: mdi:theme-light-dark

# Setup all light icons
homeassistant:
  customize:
    ##### Ground floor
    # TV
    light.living_room_iceland_1:
      icon: mdi:track-light
    light.living_room_iceland_2:
      icon: mdi:track-light
    light.attic_standing:
      icon: mdi:floor-lamp
    light.tv_led_strip:
      icon: mdi:led-strip-variant
    # Dining
    light.dining_duck:
      icon: mdi:track-light
    light.dining_large_painting:
      icon: mdi:track-light
    light.dining_table:
      icon: mdi:track-light
    # Kitchen
    light.kitchen_cooking:
      icon: mdi:track-light
    light.kitchen_kielzogschild:
      icon: mdi:track-light
    switch.kitchen_sink:
      icon: mdi:water-pump
    # Toilet
    light.toilet:
      icon: mdi:toilet
    # Closet
    light.closet:
      icon: mdi:wardrobe
    # Hall
    light.ground_floor_hall:
      icon: mdi:road-variant

    ##### First floor
    # Bedroom
    light.bedroom_closets:
      icon: mdi:rectangle-outline
    light.bedroom_thijs_bed:
      icon: mdi:bed
    # Hall
    light.first_floor_hall:
      icon: mdi:stairs
    # Computer room
    light.computers_ceiling:
      icon: mdi:desktop-tower-monitor

    ##### Second floor
    # Hall
    light.attic_hall:
      icon: mdi:washing-machine
    # Room
    switch.standing_lamp:
      icon: mdi:floor-lamp
    # Beds
    light.attic_beds:
      icon: mdi:bed

  customize_glob:
    # Motion sensors
    "sensor.motion_*": # Legacy, renaming to the one below
      icon: mdi:motion-sensor
    "sensor.*_motion_sensor*":
      icon: mdi:motion-sensor
    "binary_sensor.*_motion_sensor*":
      icon: mdi:motion-sensor
    # Remotes
    "sensor.remote_*": # Legacy, renaming to the one below
      icon: mdi:remote-tv
    "sensor.*_remote":
      icon: mdi:remote-tv
    # Identify buttons
    "button.*_identify":
      icon: mdi:card-account-details


# Light groups
# Note: for some reason these don't support an 'icon' prop, hopefully in newer versions though
light:
  # Living room lights, all of them (light.living_room_lights)
  - platform: group
    name: Living room lights
    entities:
      # TODO: more lights when installed
      - light.tv_led_strip
  # Dining room lights
  - platform: group
    name: Dining lights
    entities:
      - light.dining_table
      - light.dining_duck
      - light.dining_large_painting
  # Thijs' bedroom lights (light.bedroom_thijs_lights)
  - platform: group
    name: "Bedroom Thijs lights"
    entities:
      - light.bedroom_ceiling
      - light.bedroom_thijs_bed
  # Attic room lights (light.attic_room_lights)
  - platform: group
    name: "Attic room lights"
    entities:
      - light.attic_beds
      - light.attic_standing

input_select:
  # Living room light mode: determines brightness of all lights
  living_room_lighting_mode:
    name: Living room lighting mode
    icon: mdi:brightness-4
    options:
      - 'manual'
      - 'day'
      - 'cooking'
      - 'evening'
      - 'night'
