automation: !include_dir_merge_list automations

# Enable wake on lan integration
wake_on_lan:

# Used to detect which devices are online, and for wake-on-lan
# (this platform pings these devices each 10s or so)
switch:
  # Computer Thijs (1Gbps jack)
  # - name: Computer Thijs wake on lan
  #   platform: wake_on_lan
  #   mac: "f0:2f:74:16:19:9b"
  #   host: "10.0.1.1"
  #   broadcast_address: "10.0.1.1"
  #   turn_off:
  #     # Go to sleep instead of doing an actual shutdown
  #     action: mqtt.publish
  #     data:
  #       topic: "iotlink/workgroup/thijs/commands/suspend"
  #       payload: ""
  #   scan_interval: 6

  # Computer Thijs (2.5Gbps jack)
  - name: Computer Thijs wake on lan
    platform: wake_on_lan
    mac: "f0:2f:74:16:19:9a"
    host: "10.0.1.1"
    broadcast_address: "10.0.1.1"
    turn_off:
      # Hibernate instead of actual shutdown
      action: button.press
      target:
        entity_id: button.computer_thijs_hibernate
    scan_interval: 10
  # Laptop Thijs
  - name: Laptop Thijs wake on lan
    platform: wake_on_lan
    mac: "00:28:f8:3e:c6:82"
    host: "10.0.100.3"
    broadcast_address: "10.0.100.3"
    scan_interval: 10
  # TODO: Thijs Crisp laptop

homeassistant:
  customize:
    switch.computer_thijs_wake_on_lan:
      icon: mdi:desktop-tower-monitor
    switch.laptop_thijs_wake_on_lan:
      icon: mdi:laptop-windows

script:
  # Wake my computer
  computer_thijs_wake:
    alias: "Computer Thijs: wake up"
    sequence:
      - action: wake_on_lan.send_magic_packet
        data:
          mac: "f0:2f:74:16:19:9b"
          broadcast_address: "10.0.1.1"
