# Enable wake on lan integration
wake_on_lan:

# Used to detect which devices are online, and for wake-on-lan
# (this platform pings these devices each 10s or so)
switch:
  # Computer Thijs (1Gbps jack)
  # - name: Computer Thijs wake on lan
  #   platform: wake_on_lan
  #   mac: "f0:2f:74:16:19:9b"
  #   host: "10.0.100.1"
  #   broadcast_address: "10.0.100.1"
  #   turn_off:
  #     # Go to sleep instead of doing an actual shutdown
  #     service: mqtt.publish
  #     data:
  #       topic: "iotlink/workgroup/thijs/commands/suspend"
  #       payload: ""
  #   scan_interval: 6

  # Computer Thijs (2.5Gbps jack)
  - name: Computer Thijs wake on lan
    platform: wake_on_lan
    mac: "f0:2f:74:16:19:9a"
    host: "10.0.100.1"
    broadcast_address: "10.0.100.1"
    turn_off:
      # Go to sleep instead of doing an actual shutdown
      service: mqtt.publish
      data:
        topic: "iotlink/workgroup/thijs/commands/suspend"
        payload: ""
    scan_interval: 6
  # Laptop Thijs
  - name: Laptop Thijs wake on lan
    platform: wake_on_lan
    mac: "00:28:f8:3e:c6:82"
    host: "10.0.100.3"
    broadcast_address: "10.0.100.3"
    scan_interval: 6
  # Computer Frits
  - name: Computer Frits wake on lan
    platform: wake_on_lan
    mac: "04:d9:f5:cd:a9:cd"
    host: "10.0.100.2"
    broadcast_address: "10.0.100.2"
    scan_interval: 6
  # Laptop Frits
  - name: Laptop Frits wake on lan
    platform: wake_on_lan
    mac: "f8:ff:c2:5e:5c:b1"
    host: "10.0.100.4"
    broadcast_address: "10.0.100.4"
    scan_interval: 6

homeassistant:
  customize:
    switch.computer_thijs_wake_on_lan:
      icon: mdi:desktop-tower-monitor
    switch.laptop_thijs_wake_on_lan:
      icon: mdi:laptop-windows
    switch.computer_frits_wake_on_lan:
      icon: mdi:desktop-tower-monitor
    switch.laptop_frits_wake_on_lan:
      icon: mdi:laptop-mac

script:
  # Wake my computer
  computer_thijs_wake:
    alias: "Computer Thijs: wake up"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "f0:2f:74:16:19:9b"
          broadcast_address: "10.0.100.1"
  # iotlink notification test
  computer_thijs_notify: !include scripts/computer_thijs_notify.yaml
  # Put to sleep
  computer_thijs_suspend:
    alias: "Computer Thijs: sleep"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/thijs/commands/suspend"
          payload: ""
