- alias: "Washing machine: Idle to Off"
  description: 'From Idle to Off when it stops using power'
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      below: '3'
      # Prevent that 1 measurements turns it off
      for:
        seconds: 15
  condition:
    # Only allow from Idle
    - condition: state
      entity_id: input_select.washing_machine
      state: 'Idle'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.washing_machine
      data:
        option: "Off"


- alias: Washing machine turned off, clear notification
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.washing_machine
      from: "Idle"
      to: "Off"
  action:
    - alias: "Clear notification"
      # TODO: phone based on input_select.washing_machine_user
      service: notify.mobile_app_phone_thijs
      data:
        message: "clear_notification"
        data:
          tag: washing_machine