- alias: Washing machine done notification
  description: Indicate the washing machine is done, and allow setting marking as empty
  id: washing_machine_notify_done
  mode: parallel
  trigger:
    # State to Done
    - platform: state
      entity_id: input_select.washing_machine
      to: "Done"
  action:
    - alias: "Set up action variable"
      variables:
        action_emptied: "{{ 'EMPTIED_' ~ context.id }}"
    - alias: "Notify done, ask to empty it"
      action: >-
        {% if is_state('input_select.washing_machine_user', 'Thijs') %}
          notify.mobile_app_thijs_oneplus_13
        {% endif %}
      data:
        title: Washing machine done!
        message: Empty it and hang it to dry
        data:
          tag: washing_machine
          channel: Washing machine
          importance: high
          notification_icon: mdi:washing-machine
          clickAction: /dashboard-sections/washing
          actions:
            - action: "{{ action_emptied }}"
              title: Emptied it
              icon: sfsymbols:checkmark
    - alias: "Wait for the action (clicking the button in the notification)"
      wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_emptied }}"

    - alias: "Call the washing machine emptied script"
      action: script.washing_machine_emptied
