- alias: "Washing machine: Running to Done"
  description: 'From Running to Done when it stops using power'
  id: washing_machine_running_to_done
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      # While it is done and making noise it is around 3.2 watt
      # Drops to 0.4 watt when the noise stops after a minute or two
      below: '4'
      for:
        seconds: 10
  condition:
    # Only allow from Running
    - condition: state
      entity_id: input_select.washing_machine
      state: 'Running'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.washing_machine
      data:
        option: "Done"

