- alias: "Washing machine: Idle to Running"
  description: 'From Idle to Running when it starts to use more power'
  id: washing_machine_idle_to_running
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      # TODO: goes to ~1800-1900w when heating up water, add that as extra state?
      above: '25'
  condition:
    - condition: or
      conditions:
        # Only allow from Idle
        - condition: state
          entity_id: input_select.washing_machine
          state: 'Idle'
        # Allow from Done (restarting while not marked as done)
        # - Ideally this would detect the person that activated it again, don't want to duplicate that though
        - condition: state
          entity_id: input_select.washing_machine
          state: 'Done'
  action:
    # When coming from 'Done', detect user again (might be someone else runs it again before marked emptied)
    - if:
        - condition: state
          entity_id: input_select.washing_machine
          state: 'Done'
      then:
        - service: script.washing_machine_detect_user

    # Set the state to running
    - service: input_select.select_option
      target:
        entity_id: input_select.washing_machine
      data:
        option: "Running"
