# TODO: brightness based on time of day

# Turn on the lights when there is motion
- alias: "Attic room turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.attic_motion_sensor
      to: 'on'
  condition:
    # Only when guests mode is off, otherwise lights turn on while sleeping
    - alias: Guests mode is off
      condition: state
      entity_id: input_boolean.guests_mode
      state: 'off'
  action:
    # Turn on the lights
    - service: light.turn_on
      data:
        entity_id: light.attic_standing
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.attic_beds
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.attic_couch
        brightness: 255

    # Wait until there is no motion anymore
    # TODO: kill this, it does not work when HA reboots during it
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.attic_motion_sensor
        to: 'off'

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.attic_standing
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.attic_beds
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.attic_couch
        transition: 5