# TODO: brightness based on time of day
# TODO: different behavior in guest mode
# TODO: integrate a button for guests

# Turn on the lights when there is motion
- alias: "Attic hall turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.attic_motion_sensor
      to: 'on'
  action:
    # Turn on the lights
    - service: light.turn_on
      data:
        entity_id: light.attic_standing
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.attic_beds
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.attic_couch
        brightness: 255

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.attic_motion_sensor
        to: 'off'

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.attic_standing
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.attic_beds
        transition: 5
    - service: light.turn_off
      data:
        entity_id: light.attic_couch
        transition: 5