- alias: "Bathroom > Lights motion"
  mode: restart
  id: lighting_bathroom_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      to: 'on'
  action:
    # Turn on the light
    - alias: Set daytime variable
      variables:
        sleepy: "{{ is_state('input_boolean.thijs_sleepy', 'on') }}"
        dnd: "{{ is_state('sensor.phone_thijs_do_not_disturb', 'priority_only') }}"
    - action: light.turn_on
      data:
        entity_id: light.bathroom
        transition: 1
        brightness_pct: >-
          {% if dnd %}
            5
          {% elif sleepy %}
            50
          {% else %}
            100
          {% endif %}
        # White(r) during the day, yellow-ish at night
        color_temp_kelvin: >-
          {% if dnd %}
            2202
          {% elif sleepy %}
            2500
          {% else %}
            3500
          {% endif %}

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.bathroom_motion_sensor_occupancy
        to: 'off'

    # Turn off the light
    - action: light.turn_off
      data:
        entity_id: light.bathroom
        transition: 10 # slow turn off, time to trigger again
