- alias: "Thijs' room turn off when going to another floor"
  trigger:
    - entity_id: sensor.phone_thijs_wifi_ap
      platform: state
      from: 'first floor'
  action:
    - action: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights

- alias: "Thijs' room turn on when going out of do-not-disturb"
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'off'
  condition:
    # Only do this when Thijs is on the first floor
    - condition: "state"
      entity_id: "sensor.phone_thijs_wifi_ap"
      state: "first floor"
    - condition: "state"
      entity_id: "binary_sensor.thijs_home"
      state: "on"
  action:
    - action: script.bedroom_light_turn_on

- alias: "Thijs' room turn on when there is motion next to the bed"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_floor_motion_sensor_occupancy
      to: 'on'
  action:
    - action: script.bedroom_light_turn_on

    # Wait until there is no motion anymore for a while
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.bedroom_floor_motion_sensor_occupancy
        to: 'off'
        for:
          minutes: 1

    - alias: "Check that wide motion sensor is inactive"
      condition: state
      entity_id: binary_sensor.bedroom_wide_motion_sensor_occupancy
      state: "off"

    # Turn off the light
    - action: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights

- alias: "Thijs' room turn on when there is motion anywhere in the room"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_wide_motion_sensor_occupancy
      to: 'on'
  condition:
    # Do not disturb is off: Thijs is not sleeping yet
    - condition: 'state'
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    - action: script.bedroom_light_turn_on

    # Wait until there is no motion anymore for a while
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.bedroom_wide_motion_sensor_occupancy
        to: 'off'
        for:
          minutes: 1

    - alias: "Check that floor motion sensor is inactive"
      condition: state
      entity_id: binary_sensor.bedroom_floor_motion_sensor_occupancy
      state: "off"

    # Turn off the light
    - action: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights