# Turn on the lights when there is motion
- alias: "Living room closet turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_motion_sensor
      to: 'on'
  action:
    - action: light.turn_on
      data:
        transition: 1
        entity_id: light.closet
        brightness_pct: |-
          {% if is_state('sun.sun', 'below_horizon') %}
            50
          {% else %}
            100
          {% endif %}

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.closet_motion_sensor
        to: 'off'
        for:
          minutes: 1

    # Turn off the light
    - action: light.turn_off
      data:
        entity_id: light.closet
        transition: 5