# Turn on the lights when there is motion
- alias: "Living room closet turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_motion_sensor
      to: 'on'
  action:
    # Turn on the light
    - service: light.turn_on
      data:
        entity_id: light.closet
        brightness: 255

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.closet_motion_sensor
        to: 'off'
        for:
          minutes: 1

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.closet
        transition: 5