# Turn on the lights when there is motion
- alias: "Hall ground floor turn on when there is motion"
  mode: restart
  id: lighting_ground_floor_hall
  trigger:
    - platform: state
      entity_id: binary_sensor.ground_floor_hall_motion_sensor_occupancy
      to: 'on'
  action:
    # Turn on the light
    - service: light.turn_on
      data:
        entity_id: light.ground_floor_hall

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.ground_floor_hall_motion_sensor_occupancy
        to: 'off'
        # Hue motions sensor turns off after 10 seconds already, extends light a bit
        for:
          minutes: 1

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.ground_floor_hall
        transition: 5

# Dimmed when turned on at night
- alias: Ground floor hall light starts dimmed when turned on at night
  trigger:
    - entity_id: light.ground_floor_hall
      platform: state
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.ground_floor_hall
        brightness_pct: >-
          {% if is_state('sun.sun', 'below_horizon') %}
            20
          {% else %}
            60
          {% endif %}
        # White(r) during the day, yellow-ish at night
        # TODO: switch to Kelvin everywhere
        color_temp: >-
          {% if now().hour < 7 or now().hour >= 18 %}
            400
          {% else %}
            300
          {% endif %}