# Set the correct living room lighting mode based on the time of day and other sensors

# Day mode
- alias: 'Living room lighting mode to day'
  trigger:
    - platform: time
      at: "06:00"
  action:
    - action: script.living_room_lighting_mode
      data:
        mode: day

# Cooking mode
#- alias: 'Living room lighting mode to cooking at 18:00'
#  trigger:
#    - platform: time
#      at: "18:00"
#  action:
#    - action: script.living_room_lighting_mode
#      data:
#        mode: cooking

# Evening mode
- alias: 'Living room lighting mode to evening'
  trigger:
    - platform: time
      at: "18:30"
  action:
    - action: script.living_room_lighting_mode
      data:
        mode: evening

# Night mode
- alias: 'Living room lighting mode to night (weekend)'
  trigger:
    - platform: time
      at: "23:30"
  condition:
    - condition: time
      weekday:
      - fri
      - sat
  action:
    - action: script.living_room_lighting_mode
      data:
        mode: night
- alias: 'Living room lighting mode to night (weekday)'
  trigger:
  - platform: time
    at: "22:00"
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - action: script.living_room_lighting_mode
    data:
      mode: night

# Turn off when no-one present
- alias: Living room lights turn off (no-one present)
  id: living_room_lights_off_presence
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_in_use
      to: 'off'
      # Wait a bit before turning off, to support walking upstairs to get something
      for:
        minutes: 2
  action:
    - action: light.turn_off
      data:
        entity_id: light.living_room_lights
