- alias: "Shower > Lights motion"
  mode: restart
  id: lighting_shower_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.shower_motion_sensor_occupancy
      to: 'on'
  action:
    # Turn on the light
    - alias: Set daytime variable
      variables:
        sleepy: "{{ is_state('input_boolean.thijs_sleepy', 'on') }}"
        dnd: "{{ is_state('sensor.phone_thijs_do_not_disturb', 'priority_only') }}"
    - service: light.turn_on
      data:
        entity_id: light.shower
        brightness_pct: >-
          {% if dnd %}
            5
          {% elif sleepy %}
            20
          {% else %}
            100
          {% endif %}
        # White(r) during the day, yellow-ish at night
        kelvin: >-
          {% if dnd %}
            2202
          {% elif sleepy %}
            3000
          {% else %}
            6535
          {% endif %}

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.shower_motion_sensor_occupancy
        to: 'off'
        # Does not detect inside the shower, so keep on for quite long
        for:
          minutes: 5

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.shower
        transition: 10 # slow turn off, time to trigger again
