# Bedroom Thijs lights turn on brightness
# TODO: replacement for this (use script for turn on, and use correct brightness/color temp in there?)
# - alias: "Thijs' room lights turn on dimmed at night"
#   trigger:
#     - entity_id: light.bedroom_thijs_ceiling
#       platform: state
#       to: 'on'
#   action:
#     - service: light.turn_on
#       data:
#         entity_id: light.bedroom_thijs_ceiling
#         # Future: declare this condition once in a variable (HA 0.115+)
#         # Full bright during the day, dimmed at night
#         brightness: >-
#           {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
#             1
#           {% else %}
#             255
#           {% endif %}
#         # Warm white during night, bright white during the day
#         color_temp: >-
#           {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
#             500
#           {% else %}
#             250
#           {% endif %}

# Turn off the light when going downstairs
- alias: "Thijs' room turn off when going downstairs"
  trigger:
    - entity_id: sensor.phone_thijs_wifi_ap
      platform: state
      from: 'upstairs'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights

# Update lighting when changing do-not-disturb
- alias: "Thijs' room turn off when going into do-not-disturb"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'priority_only'
  condition:
    - condition: "state"
      entity_id: "binary_sensor.thijs_home"
      state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights
        transition: 10

- alias: "Thijs' room turn on when going out of do-not-disturb"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'off'
  condition:
    # Only do this when Thijs is upstairs
    - condition: "state"
      entity_id: "sensor.phone_thijs_wifi_ap"
      state: "upstairs"
    - condition: "state"
      entity_id: "binary_sensor.thijs_home"
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_thijs_lights
        transition: 10

# Turn on the lights when there is motion
- alias: "Thijs' room turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_thijs_motion_sensor_occupancy
      to: 'on'
  variables:
    daytime: "{{ is_state('input_boolean.thijs_sleepy', 'off') }}"
  action:
    # Turn on the led strip
    - service: light.turn_on
      data:
        entity_id: light.bedroom_thijs_bed
        brightness: >-
          {% if daytime %}
            255
          {% else %}
            38
          {% endif %}
        color_temp: >-
          {% if daytime %}
            300
          {% else %}
            495
          {% endif %}
    # Turn on the ceiling light during daytime
    - choose:
        # Turn on at daytime
        - conditions:
            - "{{ daytime }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.bedroom_thijs_ceiling
                brightness: 255
                color_temp: 250
      # Turn off at nighttime
      default:
        - service: light.turn_off
          data:
            entity_id: light.bedroom_thijs_ceiling
            transition: 5

    # Wait until there is no motion anymore for a while
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.bedroom_thijs_motion_sensor_occupancy
        to: 'off'
        for:
          minutes: 3

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.bedroom_thijs_lights


 # NFC tag test
- alias: "Light based on NFC tag"
  trigger:
    - platform: event
      event_type: tag_scanned
      event_data:
        device_id: 12945536d161848a
        tag_id: a5d1420c-898c-4f29-85f5-57a12f6e0868
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_thijs_ceiling
        brightness_pct: 50
        color_temp: 250 # Bright white
    # Debugging
    - service: notify.mobile_app_phone_thijs
      data:
        message: NFC tag scanned!
        data:
          tag: nfc
