# Turn on the lights when there is motion
- alias: "Toilet turn on when there is motion"
  id: lights_toilet_motion
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion_sensor_occupancy
      to: 'on'
  action:
    # Turn on the light
    - service: script.toilet_light_turn_on

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.toilet_motion_sensor_occupancy
        to: 'off'
        for:
          minutes: 2

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.toilet
        transition: 5
