# This seems to fix the HDMI CEC connection with the TV (which still broken in another way currently)
- alias: Batteries low update
  trigger:
    # For slow-updating things
    - platform: time_pattern
      minutes: 5
    # Couple triggers for more important ones
    - platform: state
      entity_id: sensor.thijs_oneplus_13_battery_level
  action:
    - variables:
        # The rejectattr() ones should not be required, but in devtools they are required somehow
        # I want to add             | reject('is_hidden_entity'), but that fails somehow
        batteries_low: >-
          {{
            states
            | rejectattr("attributes.device_class", 'undefined')
            | selectattr("attributes.device_class", 'equalto', 'battery')
            | rejectattr("attributes.unit_of_measurement", 'undefined')
            | selectattr("attributes.unit_of_measurement", 'equalto', '%')
            | selectattr("state", '!=', none)
            | map(attribute="state", default=0)
            | map('float', default=0)
            | min < 25
          }}
    - action: >
        {% if batteries_low %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      data:
        entity_id: input_boolean.batteries_low