# This seems to fix the HDMI CEC connection with the TV (which still broken in another way currently)
- alias: Batteries low update
  trigger:
    - platform: time_pattern
      minutes: 2
  action:
    - variables:
        batteries_low: >-
          {{
            states
            | selectattr("attributes.device_class", 'equalto', 'battery')
            | selectattr("state", '!=', 'unavailable')
            | selectattr("state", '!=', none)
            | map(attribute="state")
            | map('float')
            | min < 25
          }}
    - service: >
        {% if batteries_low %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      data:
        entity_id: input_boolean.batteries_low