# This seems to fix the HDMI CEC connection with the TV (which still broken in another way currently)
- alias: Weekly reboot
  trigger:
    - platform: time
      at: "05:00:00"
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - action: homeassistant.restart
