# Nightly reboot
# This seems to fix the HDMI CEC connection with the TV
- alias: Nightly reboot
  trigger:
    - platform: time
      at: "05:00:00"
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: homeassistant.restart
