# Turn timer on
- alias: Tree timer turn on
  trigger:
    - platform: time
      at: "9:00"
  action:
    - action: input_boolean.turn_on
      data:
        entity_id: input_boolean.tree_timer

# Turn timer off
- alias: Tree timer turn off
  trigger:
    - platform: time
      at: "22:00"
  action:
    - action: input_boolean.turn_off
      data:
        entity_id: input_boolean.tree_timer

# Apply lighting to the actual switch
- alias: Tree lighting
  trigger:
    - platform: state
      entity_id: input_boolean.tree_timer
    - platform: state
      entity_id: input_boolean.living_room_in_use
  action:
    - choose:
        # If not enabled by a timer, and no-one in the living room
        - conditions:
            - condition: state
              entity_id: input_boolean.tree_timer
              state: 'off'
            - condition: state
              entity_id: input_boolean.living_room_in_use
              state: 'off'
          sequence:
            - action: switch.turn_off
              entity_id: switch.tree
      # Else turn on
      default:
        - action: switch.turn_on
          entity_id: switch.tree