- alias: "Bedroom > Curtains open when awake"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'off'
  condition:
    # Only when home
    - condition: "state"
      entity_id: "binary_sensor.thijs_home"
      state: "on"
  action:
    # Open the curtains
    - action: cover.open_cover
      target:
        entity_id: cover.thijs_room_curtains

- alias: "Bedroom > Curtains close when going to sleep"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'priority_only'
  condition:
    # Only when home
    - condition: "state"
      entity_id: "binary_sensor.thijs_home"
      state: "on"
  action:
    # Close the curtains
    - action: cover.close_cover
      target:
        entity_id: cover.thijs_room_curtains
