- alias: Queue position remember in input text
  trigger:
    - platform: state
      entity_id: sensor.queue_processor
  condition:
    # There must be correct data in there
    - condition: state
      entity_id: sensor.queue_processor
      attribute: status
      state: 'ok'
    # Only update when different
    # (triggers of the sensor caused by force_update in the rest sensor definition)
    - condition: template
      value_template: "{{ states('sensor.queue_processor') != states('input_text.queue_processor') }}"
  action:
    # Copy it to an input_text (which is persistent across restarts)
    - action: input_text.set_value
      data:
        entity_id: input_text.queue_processor
        value: '{{ states("sensor.queue_processor") }}'

- alias: Queue position changed
  trigger:
    - platform: state
      entity_id: sensor.queue_processor_position
  action:
    # Notify Thijs
    - action: notify.mobile_app_phone_thijs
      data:
        title: >-
          Moved to position {{ states("sensor.queue_processor_position") }} in the queue for the 3950X!
        message: >-
          There are {{ states("sensor.queue_processor_total_waiting") }} people waiting in total
        data:
          tag: queue_processor_position
          channel: Processor queue
          importance: high
