type: vertical-stack
cards:
- type: vertical-stack
  title: House cleaning
  cards:
    - type: tile
      entity: input_button.last_cleaned_bathroom
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_cleaned_shower
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_cleaned_toilet
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_vacuumed_ground_floor
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_vacuumed_first_floor
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_vacuumed_attic
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_vacuumed_stairs
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_cleaned_dishwasher
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_cleaned_hood_vent
      state_content: state
      icon_tap_action:
        action: more-info
- type: vertical-stack
  title: Personal health
  cards:
    - type: tile
      entity: input_button.last_run
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_barber_cut
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_replaced_toothbrush
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_bed_sheets_change
      state_content: state
      icon_tap_action:
        action: more-info
- type: vertical-stack
  title: Maintenance
  cards:
    - type: tile
      entity: input_button.last_cleaned_shaver
      state_content: state
      icon_tap_action:
        action: more-info
    - type: tile
      entity: input_button.last_cleaned_washing_machine
      state_content: state
      icon_tap_action:
        action: more-info
- type: vertical-stack
  title: Plants
  cards:
    - type: tile
      entity: input_button.last_fed_plants
      state_content: state
      icon_tap_action:
        action: more-info
