type: custom:auto-entities
card:
  type: entities
  title: Buttons to add
filter:
  include:
  - entity_id: input_button.*
    options:
      secondary_info: last-updated
  exclude:
  - entity_id: input_button.last_run
  - entity_id: input_button.last_barber_cut
  - entity_id: input_button.last_bed_sheets_change
  - entity_id: input_button.last_cleaned_shower
  - entity_id: input_button.last_cleaned_bathroom
  - entity_id: input_button.last_cleaned_shaver
  - entity_id: input_button.last_cleaned_toilet
  - entity_id: input_button.last_cleaned_washing_machine
  - entity_id: input_button.last_fed_plants
  - entity_id: input_button.last_vacuumed_ground_floor
  - entity_id: input_button.last_vacuumed_first_floor
  - entity_id: input_button.last_vacuumed_attic
  - entity_id: input_button.last_vacuumed_stairs
  - entity_id: input_button.last_replaced_toothbrush
  - entity_id: input_button.last_cleaned_dishwasher
  - entity_id: input_button.last_cleaned_hood_vent

  - entity_id: input_button.update_crisp_integration_to_main
sort:
  method: last_updated
show_empty: false