type: vertical-stack
cards:
- type: custom:button-card
  name: ✅ Tasks
  template: header
  tap_action:
    action: navigate
    navigation_path: /dashboard-sections/tasks
- type: horizontal-stack
  cards:
    - type: tile
      name: Open
      color: yellow
      entity: todo.today
      tap_action:
        action: navigate
        navigation_path: /dashboard-sections/tasks
      icon_tap_action:
        action: navigate
        navigation_path: /dashboard-sections/tasks
      hold_action:
        action: more-info
    - type: tile
      name: Completed
      color: green
      entity: counter.tasks_completed_today
      tap_action:
        action: navigate
        navigation_path: /dashboard-sections/tasks
      icon_tap_action:
        action: navigate
        navigation_path: /dashboard-sections/tasks
      hold_action:
        action: more-info