# Persistent tracking notification
- alias: Crisp order tracking status notification
  id: crisp.tracking_status_notification
  mode: restart # When triggered another time, cancel and send notification with the latest info
  trigger:
    - platform: state
      entity_id: sensor.crisp_next_order
      attribute: details
    - platform: state
      entity_id: sensor.crisp_next_order_tracking
      attribute: eta
    - platform: state
      entity_id: sensor.crisp_next_order_raw
      attribute: fulfillStatus
  condition:
    - alias: Delivery link available
      condition: template
      value_template: "{{ state_attr('sensor.crisp_next_order_raw', 'deliveryLink') is not none }}"
    - alias: Details line is available
      condition: template
      value_template: "{{ state_attr('sensor.crisp_next_order', 'details') is not none }}"
    - alias: Order is not yet delivered/cancelled
      condition: template
      value_template: "{{ not is_state_attr('sensor.crisp_next_order_raw', 'fulfillStatus', 'done') and not is_state_attr('sensor.crisp_next_order_raw', 'fulfillStatus', 'cancel') }}"
  action:
    # Wait a bit to see if more triggers come in (which will restart the automation)
    - delay: 1
    # Send notification
    - alias: Send persistent notification
      service: notify.mobile_app_phone_thijs
      data:
        title: >-
          Crisp order
        message: >-
          {{ state_attr("sensor.crisp_next_order", "details") }}
        data:
          tag: crisp_next_order
          channel: Crisp next order
          importance: high
          sticky: "true"
          persistent: true
          alert_once: true
          notification_icon: "mdi:food-croissant"
          # Timer that counts down the minutes+seconds we are away from the ETA
          chronometer: true
          when: >-
            {{ as_timestamp(state_attr('sensor.crisp_next_order_tracking', 'eta'), default=None) | round }}
          actions:
            - action: URI
              title: Crisp app
              uri: "app://com.freshfoodventures.crisp"
            - action: URI
              title: Routigo Tracker
              uri: "{{ state_attr('sensor.crisp_next_order_raw', 'deliveryLink') }}"

# Driver is close
- alias: Crisp order driver is close
  id: crisp.driver_is_close
  trigger:
    - platform: numeric_state
      entity_id: proximity.crisp_van
      below: 150 # Meters
  action:
    - alias: Send driver is close notification
      service: notify.mobile_app_phone_thijs
      data:
        title: Crisp van is around the block!
        message: >-
          {{ states("sensor.crisp_next_order_contents") }}
        data:
          tag: crisp_next_order_close
          channel: Crisp next order
          importance: high
          notification_icon: "mdi:food-croissant"
          timeout: 60 # Remove pretty quick, persistent order notification keeps showing anyway

# Order delivered
- alias: Crisp order delivered notification
  id: crisp.delivered_notification
  trigger:
    - platform: state
      entity_id: sensor.crisp_next_order_raw
      attribute: fulfillStatus
      from: picked # Added to prevent unavailable -> done triggering notifications again
      to: done
  action:
    - alias: Send delivered notification
      service: notify.mobile_app_phone_thijs
      data:
        title: Order delivered, enjoy!
        message: >-
          {{ states("sensor.crisp_next_order_contents") }}
        data:
          tag: crisp_next_order
          channel: Crisp next order
          importance: high
          notification_icon: "mdi:food-croissant"
          timeout: 60 # Remove after a minute

# Order cancelled
- alias: Crisp order cancelled notification
  id: crisp.cancelled_notification
  trigger:
    - platform: state
      entity_id: sensor.crisp_next_order_raw
      attribute: fulfillStatus
      to: cancel
  action:
    - alias: Send cancelled notification
      service: notify.mobile_app_phone_thijs
      data:
        title: Order is cancelled!
        message: >-
          {{ states("sensor.crisp_next_order") }}
        data:
          tag: crisp_next_order
          channel: Crisp next order
          importance: high
          notification_icon: "mdi:food-croissant"
