# While there is a tracking link, update the REST sensor regularly
# TODO: dynamically enable disable this whole automation? Can increase update rate as well
- alias: Tracking link data updates
  id: crisp.tracking_update
  trigger:
    # Every minute
    - platform: time_pattern
      minutes: "/1"
  condition:
    - alias: Delivery link available
      condition: template
      value_template: "{{ not is_state_attr('sensor.crisp_next_order_raw', 'deliveryLink', None) }}"
    - alias: Order is not yet delivered/cancelled
      condition: template
      value_template: "{{ not is_state_attr('sensor.crisp_next_order_raw', 'fulfillStatus', 'done') and not is_state_attr('sensor.crisp_next_order_raw', 'fulfillStatus', 'cancel') }}"
  action:
    - alias: Update tracking link REST sensor
      service: homeassistant.update_entity
      target:
        entity_id: sensor.crisp_next_order_tracking
