# While there is a tracking link, update the REST sensor regularly
- alias: Crisp order tracking data updates
  id: crisp.tracking_update
  trigger:
    # Trigger quite often, web page of Routigo does it even more often
    - platform: time_pattern
      seconds: "/20"
  action:
    - alias: Update tracking link REST sensor
      service: homeassistant.update_entity
      target:
        entity_id: sensor.crisp_next_order_tracking

# Dynamically turn on/off the above update automation
- alias: Crisp order tracking automation enable/disable
  id: crisp.tracking_update_automation_toggle
  trigger:
    # TODO: maybe try triggering this less often?
    - platform: state
      entity_id: sensor.crisp_next_order_input
      attribute: order
  action:
    - alias: Turn on/off tracking link automation
      service: >-
        {% set order = state_attr('sensor.crisp_next_order_input', 'order') %}
        {% if order is none or order.deliveryLink is none or order.fulfillStatus == 'done' or order.fulfillStatus == 'cancel' %}
          automation.turn_off
        {% else %}
          automation.turn_on
        {% endif %}
      target:
        entity_id: automation.tracking_link_data_updates
    # TODO: trigger tracking link thing one last time to make sure it will get unavailable (to fix UI)