automation: !include_dir_merge_list automations

# WLED update command
# - you can only define 16 segments, so that is not an option for exact control
# - use the 'i' field of the 'seg' field to do individual LED range control
# - LED strip has 143 leds
rest_command:
  wled_update:
    url: http://10.0.2.46/json
    method: POST
    content_type: 'application/json'
    # Requires:
    # - payload, following the WLED JSON api: https://kno.wled.ge/interfaces/json-api/
    payload: '{{ payload }}'
