# Integration of smart curtains
automation: !include_dir_merge_list automations

# https://slide.store/
# https://www.home-assistant.io/integrations/slide
# Thijs: disabled, trying out https://github.com/ualex73/slide with support for local api
#slide:
#  username: !secret slide_username
#  password: !secret slide_password

# Setup of https://github.com/ualex73/slide
# - uses the local api
# - local api contains a call to update WIFI, see docs in Postman
cover:
- platform: slide
  host: 10.0.2.82
  password: !secret slide_device_code
