# Integration of smart curtains
automation: !include_dir_merge_list automations

# https://slide.store/
# https://www.home-assistant.io/integrations/slide
slide:
  username: !secret slide_username
  password: !secret slide_password
