- alias: Set to bluetooth mode when a phone is connected
  trigger:
    # Receiver changes source or state
    - platform: "state"
      entity_id: sensor.phone_thijs_bluetooth_connection
      attribute: connected_paired_devices
      # Thijs' phone is connected to 'BoomBoom 100', the bluetooth dongle of the home cinema setup
      to: "[88:A9:A7:DF:F9:05]"
  condition:
    # Not already set to bluetooth mode
    - condition: not
      conditions:
      - condition: "state"
        entity_id: "input_select.home_cinema_mode"
        state: "bluetooth"
  action:
    # Set to bluetooth mode
    - action: script.home_cinema_bluetooth
