# Detect pending for too long, assume something failed
- alias: Detect too long pending state
  trigger:
    - entity_id: input_boolean.home_cinema_pending
      platform: state
      to: 'on'
      # When pending for a while
      for:
        seconds: 30
  action:
    - alias: 'Set to "unknown" home cinema mode'
      action: input_select.select_option
      data:
        entity_id: input_select.home_cinema_mode
        option: "unknown"
    - alias: "Rest home cinema pending state"
      action: input_boolean.turn_off
      entity_id: input_boolean.home_cinema_pending
    - alias: "Show error notification"
      action: browser_mod.notification
      data:
        message: Switching source timed out, correct manually!
