# Detect pending for too long, assume something failed
alias: Detect too long pending state
trigger:
  - entity_id: input_boolean.home_cinema_pending
    platform: state
    to: 'on'
    # When pending for a while
    for:
      seconds: 30
action:
  # Set to 'unknown' mode
  - service: input_select.select_option
    data:
      entity_id: input_select.home_cinema_mode
      option: "unknown"
  # Reset pending
  - service: input_boolean.turn_off
    entity_id: input_boolean.home_cinema_pending
  # Notify phone of Thijs
  - service: notify.mobile_app_phone_thijs
    data:
      title: >-
        Home cinema switch to {{ states("input_select.home_cinema_mode") }} failed
      message: It was still pending after 30 seconds
      data:
        tag: home_cinema
