- alias: Home cinema state reflected in the tv led strip color
  mode: restart
  trigger:
    # Home cinema state changes
    - platform: state
      entity_id: input_select.home_cinema_mode
    # Home cinema pending state changes
    - platform: state
      entity_id: input_boolean.home_cinema_pending
  condition:
    - condition: state
      entity_id: input_boolean.living_room_in_use
      alias: "Living room is in use"
      state: 'on'
  action:
    # Update the LED strip
    # (not touching brightness, lighting feature does that)
    - action: light.turn_on
      entity_id: light.tv_led_strip
      data:
        transition: 2
        rgb_color: >-
          {% if is_state("input_boolean.home_cinema_pending", "on") %}
            {# Orange pending state #}
            {{ [175, 113, 0] }}
          {% elif is_state("input_select.home_cinema_mode", "bluetooth") %}
            {# Blue #}
            {{ [50, 50, 255] }}
          {% elif is_state("input_select.home_cinema_mode", "unknown") %}
            {# Red #}
            {{ [255, 0, 0] }}
          {% else %}
            {# Warm white default color #}
            {{ [255, 255, 220] }}
          {% endif %}
