- alias: Home cinema mode to bluetooth
  trigger:
    # Receiver changes source or state
    - platform: "state"
      entity_id: "media_player.receiver"
  condition:
    # Receiver is on
    - condition: "state"
      entity_id: "media_player.receiver"
      state: "on"
    # Receiver is on the bluetooth input
    - condition: "state"
      entity_id: media_player.receiver
      attribute: source
      state: "Bluetooth"
  action:
    # Update the mode
    - action: input_select.select_option
      data:
        entity_id: input_select.home_cinema_mode
        option: "bluetooth"
    - action: "input_boolean.turn_off"
      data:
        entity_id: "input_boolean.home_cinema_pending"
