- alias: Home cinema mode to ChromeCast (by checking chromecast state)
  trigger:
    # ChromeCast changes state
    - platform: "state"
      entity_id: "media_player.4k"
      to: "playing"
    - platform: "state"
      entity_id: "media_player.4k"
      to: "paused"
  condition:
    - condition: not
      conditions:
      # ChromeCast is not off (either 'playing' or 'paused')
      - condition: "state"
        entity_id: media_player.4k
        state: "off"
  action:
    # Update the mode
    - action: input_select.select_option
      data:
        entity_id: input_select.home_cinema_mode
        option: "chromecast"
    - action: "input_boolean.turn_off"
      data:
        entity_id: "input_boolean.home_cinema_pending"

- alias: Home cinema mode to ChromeCast (by checking Streamer state)
  trigger:
    # ChromeCast changes state
    - platform: "state"
      entity_id: "media_player.google_tv_streamer"
      to: "playing"
    - platform: "state"
      entity_id: "media_player.google_tv_streamer"
      to: "paused"
  condition:
    - condition: not
      conditions:
      # ChromeCast is not off (either 'playing' or 'paused')
      - condition: "state"
        entity_id: media_player.google_tv_streamer
        state: "off"
  action:
    # Update the mode
    - action: input_select.select_option
      data:
        entity_id: input_select.home_cinema_mode
        option: "chromecast"
    - action: "input_boolean.turn_off"
      data:
        entity_id: "input_boolean.home_cinema_pending"


- alias: Home cinema mode to ChromeCast (by checking receiver state)
  trigger:
    # Receiver changes source or state
    - platform: "state"
      entity_id: "media_player.receiver"
  condition:
    # Receiver is on
    - condition: "state"
      entity_id: "media_player.receiver"
      state: "on"
    # Receiver is on the TV input
    - condition: "state"
      entity_id: media_player.receiver
      attribute: source
      state: "TV"
    # TODO: this is not compatible with the laptop source: in both cases the receiver is set to TV, but no clue what the TV itself is on
  action:
    # Update the mode
    - action: input_select.select_option
      data:
        entity_id: input_select.home_cinema_mode
        option: "chromecast"
    - action: "input_boolean.turn_off"
      data:
        entity_id: "input_boolean.home_cinema_pending"
