# System maintenance and monitoring

automation: !include_dir_merge_list automations

# These sensors make it easy for the conditional cards in the UI,
# which have really limited boolean logic
binary_sensor:
  - platform: template
    sensors:
      # Indicates if there are HACS updates
      updates_available_hacs:
        friendly_name: "HACS updates available"
        # Also deals with the 'None' value that is present during startup
        value_template: "{{ not is_state('sensor.hacs', 'unavailable') and states('sensor.hacs') is not none and not is_state('sensor.hacs', '0') }}"

      # Indicates if there are any HA or HACS updates
      updates_available:
        friendly_name: "Updates available"
        value_template: "{{ is_state('update.home_assistant_core_update', 'on') or is_state('binary_sensor.updates_available_hacs', 'on') }}"

input_boolean:
  # Tracks if there are devices with low batteries
  batteries_low:
    name: Batteries low
    icon: mdi:battery-charging-20
    initial: off

# Enable this integration (which does autodiscovery using the UI)
battery_notes:
  round_battery: true # Whole numbers instead of 10.0 and such
  hide_battery: true # Hide the original battery entity