# Virtual power sensors (based on time that lights are on)
# Note: there is no built-in profile for the Ikea light panels yet, see: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md#supported-models
# TODO: measure power usage of missing lights, contribute to the repo?

powercalc:
  # I don't need a sensor for each light, just a couple of aggregated ones defined below
  enable_autodiscovery: false
  scan_interval: 00:05:00 # Each 5 minutes (prevent spammy updates)

# Device reference list: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md
sensor:
  ########## LIGHTS
  # Sensor for all spots in the living room
  - platform: powercalc
    entity_id: light.dining_duck # Random entity id, to base default ids on
    name: Living room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 7
    multiply_factor_standby: true
  # TV LED strip
  - platform: powercalc
    entity_id: light.tv_led_strip
    manufacturer: signify
    model: LST002
  # Room Thijs: FLOALT panel WS 30x90
  - platform: powercalc
    entity_id: light.bedroom_thijs_ceiling
    manufacturer: ikea
    model: L1528
  # Computer Room: FLOALT panel WS 30x30
  - platform: powercalc
    entity_id: light.computers_ceiling
    manufacturer: ikea
    model: L1527
  # Attic color-changing light: TRADFRI bulb E27 CWS opal 600lm
  - platform: powercalc
    entity_id: light.attic_standing
    manufacturer: ikea
    model: LED1624G9
  # WLED CO2 LED strip
  - platform: powercalc
    entity_id: sensor.quinled_dig_uno_estimated_current
    wled:
      voltage: 12
  # Frits' room
  - platform: powercalc
    entity_id: light.frits_room_wall # Random entity id, to base default ids on
    name: Frits' room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 3
    multiply_factor_standby: true
  ######### DEVICES
  - platform: powercalc
    name: T-mobile TV energy
    daily_fixed_energy:
      # Measured standby usage (around 4 watt when in-use), just always use standby since it is rarely on
      value: 3
      unit_of_measurement: W
  - platform: powercalc
    name: Living Room Google Home energy
    daily_fixed_energy:
      # Measured standby usage
      value: 1.6
      unit_of_measurement: W
  - platform: powercalc
    name: Steam link energy
    daily_fixed_energy:
      # Measured standby usage
      value: 0.9
      unit_of_measurement: W

# Sensor for all living room lights summed together
template:
  - sensor:
      - name: "Living room lights energy"
        unit_of_measurement: kWh
        state: >
          {{
            states('sensor.living_room_spots_energy') | float(default=0)
            + states('sensor.tv_led_strip_energy') | float(default=0)
            + states('sensor.kitchen_sink_energy') | float(default=0)
          }}
        attributes:
          last_reset: "1970-01-01T00:00:00+00:00"
          state_class: total_increasing
          device_class: energy
          icon: mdi:counter
  - sensor:
      - name: "Living room lights power"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.living_room_spots_power') | float(default=0)
            + states('sensor.tv_led_strip_power') | float(default=0)
            + states('sensor.kitchen_sink_power') | float(default=0)
          }}
        device_class: power
        state_class: measurement
        icon: mdi:transmission-tower
  - sensor:
      - name: "Power consumption (watt)"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.power_consumption') | float(default=0) * 1000
          }}
        device_class: power
        state_class: measurement
        icon: mdi:lightning-bolt-circle
