# Virtual power sensors (based on time that lights are on)

powercalc:

# Device reference list: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md
sensor:
  ########## LIGHTS
  # TODO: move all to UI configuration
  # Sensor for all spots in the living room
  - platform: powercalc
    entity_id: light.dining_duck # Random entity id, to base default ids on
    name: Living room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 7
    multiply_factor_standby: true
  # WLED CO2 LED strip
  - platform: powercalc
    entity_id: sensor.quinled_dig_uno_estimated_current
    wled:
      voltage: 12
  # Frits' room
  - platform: powercalc
    entity_id: light.frits_room_wall # Random entity id, to base default ids on
    name: Frits' room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 3
    multiply_factor_standby: true

# Sensor for all living room lights summed together
# TODO: use grouping in UI of powercalc instead?
template:
  - sensor:
      - name: "Living room lights energy"
        unit_of_measurement: kWh
        state: >
          {{
            states('sensor.living_room_spots_energy') | float(default=0)
            + states('sensor.tv_led_strip_energy') | float(default=0)
            + states('sensor.kitchen_sink_energy') | float(default=0)
          }}
        attributes:
          last_reset: "1970-01-01T00:00:00+00:00"
          state_class: total_increasing
          device_class: energy
          icon: mdi:counter
  - sensor:
      - name: "Living room lights power"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.living_room_spots_power') | float(default=0)
            + states('sensor.tv_led_strip_power') | float(default=0)
            + states('sensor.kitchen_sink_power') | float(default=0)
          }}
        device_class: power
        state_class: measurement
        icon: mdi:transmission-tower
  - sensor:
      - name: "Power consumption (watt)"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.power_consumption') | float(default=0) * 1000
          }}
        device_class: power
        state_class: measurement
        icon: mdi:lightning-bolt-circle
