# Virtual power sensors (based on time that lights are on)
# Note: there is no built-in profile for the Ikea light panels yet, see: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md#supported-models
# TODO: measure power usage of missing lights, contribute to the repo?

powercalc:
  scan_interval: 00:05:00 # Each 5 minutes (prevent spammy updates)

sensor:
  # Sensor for all spots in the living room
  - platform: powercalc
    entity_id: light.dining_duck # Random entity id, to base default ids on
    name: Living room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 7
    multiply_factor_standby: 7
  # TV LED strip
  - platform: powercalc
    entity_id: light.tv_led_strip
    manufacturer: signify
    model: LST002

# Sensor for all living room lights summed together
template:
  - sensor:
      - name: "Living room lights energy"
        unit_of_measurement: kWh
        state: >
          {{
            states('sensor.living_room_spots_energy') | float
            + states('sensor.tv_led_strip_energy') | float
            + states('sensor.kitchen_sink_energy') | float
          }}
        attributes:
          last_reset: "1970-01-01T00:00:00+00:00"
          state_class: total_increasing
          device_class: energy
          icon: mdi:counter
