# Virtual power sensors (based on time that lights are on)

powercalc:
  # I don't need a sensor for each light, just a couple of aggregated ones defined below
  enable_autodiscovery: false

# Device reference list: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md
sensor:
  ########## LIGHTS
  # Sensor for all spots in the living room
  - platform: powercalc
    entity_id: light.dining_duck # Random entity id, to base default ids on
    name: Living room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 7
    multiply_factor_standby: true
  # TV LED strip
  - platform: powercalc
    entity_id: light.tv_led_strip
    manufacturer: signify
    model: LST002
  # Living room closet
  - platform: powercalc
    entity_id: light.closet
    manufacturer: ikea
    model: LED1623G12
  # Ground floor hall
  - platform: powercalc
    entity_id: light.ground_floor_hall
    manufacturer: ikea
    model: LED1623G12
  # Toilet
  - platform: powercalc
    entity_id: light.toilet
    manufacturer: ikea
    model: LED1623G12
  # First floor hall
  - platform: powercalc
    entity_id: light.first_floor_hall
    manufacturer: ikea
    model: LED1623G12
  # Room Thijs: FLOALT panel WS 30x90
  - platform: powercalc
    entity_id: light.bedroom_thijs_ceiling
    manufacturer: ikea
    model: L1528
  # Computer Room: FLOALT panel WS 30x30
  - platform: powercalc
    entity_id: light.computers_ceiling
    manufacturer: ikea
    model: L1527
  # Attic color-changing light: TRADFRI bulb E27 CWS opal 600lm
  - platform: powercalc
    entity_id: light.attic_standing
    manufacturer: ikea
    model: LED1624G9
  # WLED CO2 LED strip
  - platform: powercalc
    entity_id: sensor.quinled_dig_uno_estimated_current
    wled:
      voltage: 12
  # Frits' room
  - platform: powercalc
    entity_id: light.frits_room_wall # Random entity id, to base default ids on
    name: Frits' room spots
    manufacturer: ikea
    model: LED1650R5
    multiply_factor: 3
    multiply_factor_standby: true
  # Attic beds
  - platform: powercalc
    entity_id: light.attic_beds
    manufacturer: ikea
    model: LED1935C3
  # Attic couch
  - platform: powercalc
    entity_id: light.attic_couch
    manufacturer: ikea
    model: LED1935C3
  # Attic hall
  - platform: powercalc
    entity_id: light.attic_hall
    manufacturer: ikea
    model: LED1623G12
  ######### DEVICES
  - platform: powercalc
    name: T-mobile TV
    unique_id: 6093f88e-608d-4cba-b842-99acb4a1ddc9
    daily_fixed_energy:
      # Measured standby usage (around 4 watt when in-use), just always use standby since it is rarely on
      value: 3
      unit_of_measurement: W
  - platform: powercalc
    name: Powerline adapters
    unique_id: e6e5a0f6-ac44-4e48-9dd5-2b9cdfb2f850
    daily_fixed_energy:
      # Measured standby usage, multiplied by 2
      value: 4.2
      unit_of_measurement: W
  - platform: powercalc
    name: Living Room Google Home
    unique_id: 660f2329-3889-4c55-92a9-0eb1ff3eb94b
    daily_fixed_energy:
      # Measured standby usage
      value: 1.6
      unit_of_measurement: W
  - platform: powercalc
    name: Steam link energy
    unique_id: f71009cb-3dcb-49b6-bfec-3732d78397cb
    daily_fixed_energy:
      # Measured standby usage
      value: 0.9
      unit_of_measurement: W
  - platform: powercalc
    name: Switch energy # Meterkast
    unique_id: 3ce299cc-3f28-422d-b35b-48533c1d9342
    daily_fixed_energy:
      # Measured standby usage
      value: 4,7
      unit_of_measurement: W
  - platform: powercalc
    name: Unifi Security Gateway
    unique_id: acfa404f-cd76-4f60-9b57-81199b5a8478
    daily_fixed_energy:
      # Measured standby usage
      value: 8
      unit_of_measurement: W
  - platform: powercalc
    name: POE access point living room
    unique_id: 95936c3d-9a7b-44d1-a930-98f17d65f920
    daily_fixed_energy:
      # Measured standby usage
      value: 3.7
      unit_of_measurement: W
  - platform: powercalc
    name: POE access point room Thijs
    unique_id: ae62bb42-ffab-4748-a37e-3fdc567a1c46
    daily_fixed_energy:
      # Measured standby usage
      value: 3.7
      unit_of_measurement: W
  # Disabled now, directly using the Ubiquiti USG
  #- platform: powercalc
  #  name: T-Mobile modem energy
  #  unique_id: b3e60978-da9c-4a61-8e1e-599b01682507
  #  daily_fixed_energy:
  #    # Measured standby usage, varies a bit by usage, but not much
  #    value: 6.6
  #    unit_of_measurement: W

# Sensor for all living room lights summed together
# TODO: use grouping of powercalc instead?
template:
  - sensor:
      - name: "Living room lights energy"
        unit_of_measurement: kWh
        state: >
          {{
            states('sensor.living_room_spots_energy') | float(default=0)
            + states('sensor.tv_led_strip_energy') | float(default=0)
            + states('sensor.kitchen_sink_energy') | float(default=0)
          }}
        attributes:
          last_reset: "1970-01-01T00:00:00+00:00"
          state_class: total_increasing
          device_class: energy
          icon: mdi:counter
  - sensor:
      - name: "Living room lights power"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.living_room_spots_power') | float(default=0)
            + states('sensor.tv_led_strip_power') | float(default=0)
            + states('sensor.kitchen_sink_power') | float(default=0)
          }}
        device_class: power
        state_class: measurement
        icon: mdi:transmission-tower
  - sensor:
      - name: "Power consumption (watt)"
        unit_of_measurement: W
        state: >
          {{
            states('sensor.power_consumption') | float(default=0) * 1000
          }}
        device_class: power
        state_class: measurement
        icon: mdi:lightning-bolt-circle
