# Virtual power sensors (based on time that lights are on)
# Note: there is no built-in profile for the Ikea light panels yet, see: https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md#supported-models
# TODO: measure power usage of missing lights, contribute to the repo?
sensor:
  - platform: powercalc
    entity_id: light.kitchen_cooking
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.kitchen_kielzogschild
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.dining_table
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.dining_duck
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.dining_large_painting
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.living_room_iceland_1
    manufacturer: ikea
    model: LED1650R5
  - platform: powercalc
    entity_id: light.living_room_iceland_2
    manufacturer: ikea
    model: LED1650R5

  - platform: template
    sensors:
      # Note: tv led strip and kitchen counter lights are currently missing (don't have energy sensors yet)
      living_room_lights_energy:
        friendly_name: "Living room lights energy"
        unit_of_measurement: kWh
        value_template: >-
          {{
            states('sensor.kitchen_cooking_energy') | float
            + states('sensor.kitchen_kielzogschild_energy') | float
            + states('sensor.dining_table_energy') | float
            + states('sensor.dining_duck_energy') | float
            + states('sensor.dining_large_painting_energy') | float
            + states('sensor.living_room_iceland_1_energy') | float
            + states('sensor.living_room_iceland_2_energy') | float
          }}
        attribute_templates:
          last_reset: "1970-01-01T00:00:00+00:00"
          state_class: measurement
          device_class: energy
          icon: mdi:counter