# Implements lights control

automation: !include_dir_merge_list automations

input_boolean:
  # Tracks in someone is in the living room
  living_room_in_use:
    name: Living room in use
    icon: mdi:sofa
  thijs_sleepy:
    name: Thijs is sleepy
    icon: mdi:sleep

sensor:
  - platform: template
    sensors:
      # Floor that Thijs' phone is using
      phone_thijs_wifi_ap:
        friendly_name: "Phone Thijs Wifi AP"
        value_template: >-
          {% if is_state_attr('device_tracker.unifi_phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}
            downstairs
          {% elif is_state_attr('device_tracker.unifi_phone_thijs', 'ap_mac', '18:e8:29:90:45:62') %}
            upstairs
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.phone_thijs_wifi_ap', 'downstairs') %}
            mdi:home-floor-0
          {% elif is_state('sensor.phone_thijs_wifi_ap', 'upstairs') %}
            mdi:home-floor-1
          {% else %}
            mdi:home-remove-outline
          {% endif %}
      # Floor that Thijs' laptop is using
      laptop_thijs_wifi_ap:
        friendly_name: "Laptop Thijs Wifi AP"
        value_template: >-
          {% if is_state_attr('device_tracker.unifi_laptop_thijs', 'ap_mac', '18:e8:29:90:42:42') %}
            downstairs
          {% elif is_state_attr('device_tracker.unifi_laptop_thijs', 'ap_mac', '18:e8:29:90:45:62') %}
            upstairs
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.laptop_thijs_wifi_ap', 'downstairs') %}
            mdi:home-floor-0
          {% elif is_state('sensor.laptop_thijs_wifi_ap', 'upstairs') %}
            mdi:home-floor-1
          {% else %}
            mdi:home-remove-outline
          {% endif %}
      # Floor that Frits' phone is using
      phone_frits_wifi_ap:
        friendly_name: "Phone Frits Wifi AP"
        value_template: >-
          {% if is_state_attr('device_tracker.unifi_phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}
            downstairs
          {% elif is_state_attr('device_tracker.unifi_phone_frits', 'ap_mac', '18:e8:29:90:45:62') %}
            upstairs
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.phone_frits_wifi_ap', 'downstairs') %}
            mdi:home-floor-0
          {% elif is_state('sensor.phone_frits_wifi_ap', 'upstairs') %}
            mdi:home-floor-1
          {% else %}
            mdi:home-remove-outline
          {% endif %}
      # Floor that Frits' laptop is using
      laptop_frits_wifi_ap:
        friendly_name: "Laptop Frits Wifi AP"
        value_template: >-
          {% if is_state_attr('device_tracker.unifi_laptop_frits', 'ap_mac', '18:e8:29:90:42:42') %}
            downstairs
          {% elif is_state_attr('device_tracker.unifi_laptop_frits', 'ap_mac', '18:e8:29:90:45:62') %}
            upstairs
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.laptop_frits_wifi_ap', 'downstairs') %}
            mdi:home-floor-0
          {% elif is_state('sensor.laptop_frits_wifi_ap', 'upstairs') %}
            mdi:home-floor-1
          {% else %}
            mdi:home-remove-outline
          {% endif %}

      # Thijs' location
      thijs_location:
        friendly_name: "Thijs' location"
        value_template: >-
          {% if is_state('sensor.phone_thijs_wifi_ap', 'away') %}
            {% if is_state('device_tracker.phone_thijs', 'not_home') %}
              Away
            {% else %}
              {{ states('device_tracker.phone_thijs').capitalize() }}
            {% endif %}
          {% else %}
            {{ states('sensor.phone_thijs_wifi_ap').capitalize() }}
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.phone_thijs_wifi_ap', 'away') %}
            {# Not on wifi, use phone location tracker #}
            {% if is_state('device_tracker.phone_thijs', 'not_home') %}
              {# Away #}
              mdi:run-fast
            {% else %}
              {# Get the icon from the active zone (sadly not set as attribute on the device_tracker) #}
              {{
                states.zone
                | selectattr("entity_id", "equalto", "zone." + (states("device_tracker.phone_thijs") | lower | trim('0')))
                | map(attribute="attributes.icon")
                | first
                | default('mdi:alert')
              }}
            {% endif %}
          {% else %}
            {# On wifi, use icon of that tracker (indicates floor) #}
            {{ state_attr('sensor.phone_thijs_wifi_ap', 'icon') }}
          {% endif %}

      # Frits' location
      frits_location:
        friendly_name: "Frits' location"
        value_template: >-
          {% if is_state('sensor.phone_frits_wifi_ap', 'away') %}
            {% if is_state('device_tracker.phone_frits', 'not_home') %}
              Away
            {% else %}
              {{ states('device_tracker.phone_frits').capitalize() }}
            {% endif %}
          {% else %}
            {{ states('sensor.phone_frits_wifi_ap').capitalize() }}
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.phone_frits_wifi_ap', 'away') %}
            {# Not on wifi, use phone location tracker #}
            {% if is_state('device_tracker.phone_frits', 'not_home') %}
              {# Away #}
              mdi:run-fast
            {% else %}
              {# Get the icon from the active zone (sadly not set as attribute on the device_tracker) #}
              {{
                states.zone
                | selectattr("entity_id", "equalto", "zone." + (states("device_tracker.phone_frits") | lower | trim('0')))
                | map(attribute="attributes.icon")
                | first
                | default('mdi:alert')
              }}
            {% endif %}
          {% else %}
            {# On wifi, use icon of that tracker (indicates floor) #}
            {{ state_attr('sensor.phone_frits_wifi_ap', 'icon') }}
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      # Someone present in the living room
      living_room_used_wifi:
        friendly_name: "Living room AP in use"
        device_class: occupancy
        value_template: >-
          {% if is_state('sensor.phone_thijs_wifi_ap', 'downstairs') or is_state('sensor.phone_frits_wifi_ap', 'downstairs') %}
            yes
          {% else %}
            no
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.phone_thijs_wifi_ap', 'downstairs') and is_state('sensor.phone_frits_wifi_ap', 'downstairs') %}
            mdi:account-multiple
          {% elif is_state('sensor.phone_thijs_wifi_ap', 'downstairs') or is_state('sensor.phone_frits_wifi_ap', 'downstairs') %}
            mdi:account
          {% else %}
            mdi:account-off
          {% endif %}
      # Computer room used based on computer activity
      # Future: add tracking for Frit's laptop (stays connected while sleeping, so we need activity sensor of the companion app first)
      computer_room_used_devices:
        friendly_name: "Computer room in use"
        device_class: occupancy
        value_template: >-
          {% if is_state('switch.computer_thijs_wake_on_lan', 'on') or is_state('switch.computer_frits_wake_on_lan', 'on') or is_state('sensor.laptop_thijs_wifi_ap', 'upstairs') %}
            yes
          {% else %}
            no
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.computer_room_used_devices', 'on') %}
            mdi:account-multiple
          {% else %}
            mdi:account-off
          {% endif %}
      thijs_home:
        friendly_name: "Thijs is home"
        device_class: presence
        value_template: >-
          {% if not is_state('sensor.phone_thijs_wifi_ap', 'away') or is_state('device_tracker.phone_thijs', 'home') %}
            yes
          {% else %}
            no
          {% endif %}