- alias: CO2 in the computer room is getting high
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_computers_co2
      above: '1000'
    # Repeat when even higher
    - platform: numeric_state
      entity_id: sensor.netatmo_computers_co2
      above: '1300'
  action:
    - service: notify.computer_thijs
      data:
        title: The CO2 level is at {{states("sensor.netatmo_computers_co2")}} ppm!
        message: Open a window to fix it
    # Flash the lights
    - repeat:
        count: 6
        sequence:
          - delay: 1
          - service: light.toggle
            data:
              entity_id: light.computers_ceiling
