- alias: CO2 in the living room is getting high
  trigger:
    - platform: numeric_state
      entity_id: sensor.ecowitt_wh45_co2
      above: '1000'
    # Repeat when even higher
    - platform: numeric_state
      entity_id: sensor.ecowitt_wh45_co2
      above: '1300'
  action:
    - service: notify.mobile_app_phone_thijs
      data:
        title: Living room CO2 is at {{states("sensor.ecowitt_wh45_co2")}} ppm!
        message: Open a window to fix it
        data:
          tag: co2_living_room
          channel: CO2
          importance: high
          notification_icon: mdi:molecule-co2
    # Save the current state of the lights
    - service: scene.create
      data:
        scene_id: living_room_lights_before_co2_alert
        snapshot_entities:
        # How to specify all light.living_room_lights?
          - light.living_room_lights
    # Flash the lights
    # TODO: works great for led strip, but not for the spots, use manual on/off for those?
    - service: light.turn_on
      data:
        flash: long
        # Lights that don't support red will just use white
        color_name: red
      target:
        # Living room
        area_id: 78b5d262f52447289d44580143271ebc
    # Set the volume of the Google Home mini to 40%
    #- service: media_player.volume_set
    #  target:
    #    entity_id: media_player.living_room_google_home_mini
    #  data:
    #    volume_level: 0.4
    # Let the Google Home mini shout
    #- service: tts.google_cloud_say
    #  data:
    #    entity_id: media_player.living_room_google_home_mini
    #    message: >-
    #        CO2 is at {{states("sensor.ecowitt_wh45_co2")}} ppm, open a window
    #    cache: false # Contains a template, caching does not really work
    # Restore the living room lights after the flashing is done
    - alias: "Wait until the lights are done flashing"
      delay:
        seconds: 13
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_lights_before_co2_alert
    # Reload scenes, which gets rid of the temporary one created above (scene.create should override, but that does not work currently it looks like)
    - service: scene.reload
