- alias: CO2 in Thijs' bedroom is getting high
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_bedroom_co2
      above: 1000
  action:
    # Notify phone of Thijs
    - action: notify.mobile_app_thijs_oneplus_13
      data:
        title: >-
          Bedroom CO2 is at {{ states("sensor.netatmo_bedroom_co2") }} ppm!
        message: Open the window!
        data:
          tag: co2_bedroom
          channel: CO2
          importance: high
          notification_icon: mdi:molecule-co2