# Toggle monitor Thijs based on computer usage and being home
- alias: Computer monitor Thijs toggle based on presence
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_thijs_used
    - platform: state
      entity_id: binary_sensor.thijs_home
  action:
    - service: >
        {% if is_state('binary_sensor.computer_thijs_used', 'on') and is_state('binary_sensor.thijs_home', 'on') %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      data:
        entity_id: switch.monitor_thijs
