# Toggle monitor Thijs based on computer usage and being home
- alias: Computer monitor Thijs toggle based on presence
  id: presence_computer_monitor_thijs
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_thijs_used
    - platform: state
      entity_id: binary_sensor.thijs_home
      # Delay a bits
      for:
        seconds: 10
  action:
    # When one of the sensors is unavailable: keep monitor turned on
    - action: >
        {% if not is_state('binary_sensor.computer_thijs_used', 'off') and not is_state('binary_sensor.thijs_home', 'off') %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      data:
        entity_id: switch.monitor_thijs
