# Map the ap detection to the living room presence input
- alias: Detect phones downstairs
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_used_wifi
  action:
    - service: >
        {% if is_state('binary_sensor.living_room_used_wifi', 'on') %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      data:
        entity_id: input_boolean.living_room_in_use

# Map the motion sensor to the living room presence input
- alias: Detect motion in the living room
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor_occupancy
      to: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_in_use

- alias: Detect no motion in the living room
  trigger:
    # Trigger after no motion for a while
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor_occupancy
      to: 'off'
      for:
        minutes: 5
  condition:
    # Don't turn off if there is still someone present
    - condition: state
      entity_id: binary_sensor.living_room_used_wifi
      state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.living_room_in_use
