# Update based on phone vibrate setting
- alias: Set sleepy when phone to ring mode
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_audio_setting
      to: normal
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.thijs_sleepy
  mode: single

- alias: Unset sleepy when phone goes to vibrate mode
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_audio_setting
      to: vibrate
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.thijs_sleepy
  mode: single

# Update based on time
- alias: Sleepy after 22:00 during the week
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: time
      alias: Weekday
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.thijs_sleepy
- alias: Sleepy after 23:59 during the weekend
  trigger:
    - platform: time
      at: "23:59:00"
  condition:
    - condition: time
      alias: Weekend
      weekday:
        - fri
        - sat
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.thijs_sleepy
