- alias: LetsEncrypt certificate renewal for secrets.no_ip_domain
  trigger:
    - platform: time
      # An hour before the daily restart
      at: '04:00:00'
  action:
    - service: hassio.addon_start
      data:
        addon: core_letsencrypt
