# Run a speedtest each night (which won't affect internet usage during the day)
- alias: Nightly internet speedtest
  trigger:
    - platform: time
      at: "06:00:00"
  action:
    - action: homeassistant.update_entity
      # Targeting the download speed entity, but this will update ping and upload as well
      entity_id: sensor.speedtest_download
