# Weather tracking components and UI

automation: !include_dir_merge_list automations

# Night sensor to use in graphs
binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
  - platform: tod
    name: Day
    after: sunrise
    before: sunset

sensor:
  # Sensor for the elevation of the sun (makes it easy to work with in graphs)
  - platform: template
    sensors:
      solar_elevation:
        friendly_name: "Sun elevation"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  # 'feels like' temperature sensor
  - platform: temperature_feels_like
    name: "Outside 'feels like' temperature"
    unique_id: temperature_feels_like_outside
    source:
      - sensor.netatmo_garden_temperature
      - sensor.netatmo_garden_humidity
      # Using the 'gust' wind speed (meaning the result will be a worst-case temperature I guess)
      - sensor.netatmo_wind_gust_strength

template:
  - binary_sensor:
      name: "Fridge temperature bad"
      unique_id: '6aadae15-f9b9-4c30-bb96-c567bf276bc8'
      state: "{{ (states('sensor.fridge_temperature') | float(default=20)) < 0 or (states('sensor.fridge_temperature') | float(default=20)) > 8 }}"
      device_class: problem
      availability: >-
        {{ states('sensor.fridge_temperature') is not none }}

# Indoor air quality combination
# TODO: this integration needs an update, uses old/removed HA function
#iaquk:
#  living_room:
#    name: Living room
#    sources:
#      temperature: sensor.ecowitt_wh45_temperature
#      humidity: sensor.ecowitt_wh45_humidity
#      co2: sensor.ecowitt_wh45_co2
#      pm:
#        - sensor.ecowitt_wh45_pm2_5
#        - sensor.ecowitt_wh45_pm10
