# Weather tracking components and UI

automation: !include_dir_merge_list automations

# Night sensor to use in graphs
binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
  - platform: tod
    name: Day
    after: sunrise
    before: sunset

sensor:
  # Sensor for the elevation of the sun (makes it easy to work with in graphs)
  - platform: template
    sensors:
      solar_elevation:
        friendly_name: "Sun elevation"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
  # 'feels like' temperature sensor
  - platform: temperature_feels_like
    name: "Outside 'feels like' temperature"
    unique_id: temperature_feels_like_outside
    source:
      - sensor.netatmo_garden_temperature
      - sensor.netatmo_garden_humidity
      # Using the 'gust' wind speed (meaning the result will be a worst-case temperature I guess)
      - sensor.netatmo_wind_gust_strength
